allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  vue-demi: true

peerDependencyRules:
  allowedVersions:
    mockjs: 0.3.7

overrides:
  'vite-plugin-mock>path-to-regexp': 6.3.0
