const metaProps = [
  {
    title: '图表',
    type: 'chart',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '折线图',
    chartType: 'line',
    props: {},
  },
  {
    title: '信息',
    type: 'view',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '文字',
    chartType: 'text',
    props: {},
  },
  {
    title: '列表',
    type: 'list',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '滚动列表',
    chartType: 'table',
    props: {},
  },
  {
    title: '组件',
    type: 'components',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '折线图',
    chartType: 'line-1',
    props: {},
  },
  {
    title: '图表',
    type: 'chart',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '边框',
    chartType: 'frame',
    props: {},
  },
  {
    title: '图表',
    type: 'chart',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '柱状图',
    chartType: 'bar',
    props: {},
  },
  {
    title: '信息',
    type: 'view',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '控件',
    chartType: 'control',
    props: {},
  },
  {
    title: '图表',
    type: 'chart',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '折线图',
    chartType: 'line-1',
    props: {},
  },
  {
    title: '图表',
    type: 'chart',
    groupTitle: '所有',
    groupType: 'all',
    chartTitle: '折线图',
    chartType: 'line-1',
    props: {},
  },
];
